name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Setup Git for tests
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"

      - name: Generate test repository
        run: ./tests/scripts/generate-test-repo.sh

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build
